version: '3.5'

services:
  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root      
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ENTRYPOINT_INITDB: ./mysql/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - network-mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - 8089:8080
    networks:
      - network-mysql
    restart: unless-stopped

networks: 
  network-mysql:
    driver: bridge