version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "S@102030"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8089:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge