version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
     #  - ./postgres-data:/data/postgres
       - "./data/postgres:/var/lib/postgresql/data"
       - "./data/pgdata:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - network-postgre
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.13
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - network-postgre
    restart: unless-stopped

networks:
  network-postgre:
    driver: bridge
