version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p102030}
      PGDATA: /data/postgres
    volumes:
       - postgres-data:/data/postgres
    ports:
      - 5432:5432
    networks:
      - devnetwork
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin-data:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - devnetwork
    restart: unless-stopped
  
  activemq:
    container_name: artemis
    image: vromero/activemq-artemis:2.6-alpine-latest 
    ports:
      - 8161:8161 
      - 61616:61616
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: 102030
    networks:
      - devnetwork
    restart: unless-stopped

networks:
  devnetwork:
    driver: bridge

volumes:
    postgres-data:
    pgadmin-data: