version: "3.6"

services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - environment-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://0.0.0.0:5432/sonar
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=p102030
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  environment-network:
    driver: bridge


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

